#FROM lib.iot.sedt.com/ubuntu-java:8
FROM lib.iot.sedt.com/arm64v8/openjdk:jdk-oraclelinux8
WORKDIR /ms
MAINTAINER William
ENV DEBIAN_FRONTEND noninteractive

COPY target/*.jar /ms/app.jar

COPY src/main/resources/config_prod /ms/config_prod

COPY setEnvironment.sh /ms/setEnvironment.sh
RUN chmod +x /ms/setEnvironment.sh
COPY version.txt /ms/version.txt


COPY docker-entrypoint.sh /usr/bin/docker-entrypoint.sh
RUN chmod +x /usr/bin/docker-entrypoint.sh
ENTRYPOINT ["docker-entrypoint.sh"]



